# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YourApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YourApp
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Localize-Swift', '~> 1.7'
  pod 'SVProgressHUD', '~> 2.1'

  target 'YourAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YourAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
